### ISSUE TITLE
Atom gets very slow, rspec run on every save/switch file

### ISSUE THREAD

**Issue by rngtng** [Jacob84/rspec-tree-runner#12]
Wow, thanks  for that great package, it's a very nice rspec integration and works quite well for me. Unfortunately atom gets quite slow after a couple of testruns. Any idea what this could be? In addition it show "running test" on the right everytime I save or switch to a different rspec file, but it's actually not running the test, I think it's parsing the file? Thanks!

**Comment by jacobmendoza** [comment]
Hi @rngtng,

Thanks a lot for your feedback. I really appreciate your words.

Probably, as you were saying, will be the parsing of the RSpec file. My experience with Ruby is limited and the script that does the parsing was born more as an experiment than like a real project. Also, to be honest, parsing the file is not the easiest thing.

I know that several improvements could be made: 
- Review the entire parsing script. Probably too complex.
- Saving the serialization of the generated tree and only update it when necessary.
- Review the memory management of the plugin. I must review this, as some things may be wrong. 

I'm planning to spend a few hours this week reviewing this and also the other issues posted. Hopefully I'll find ways to improve it. I'll keep you posted.

Again, thanks :)

**Comment by sibevin** [comment]
I have the same issue, especially in large rspec files.

For me, it is not necessary to refresh the tree view or run tests immediately when the file is changed or switched. Maybe providing an option to turn on/off the automation and a hotkey to refresh the tree view is a way to solve this issue.

**Comment by jacobmendoza** [comment]
Hi @sibevin, thank you very much for adding your experience and suggestions.

I'm planning to do a major rewrite of the plugin and migrate the code from CoffeeScript to ES6. I'm completely aware that the rewrite by itself won't solve the problem, but will give me a better chance of fixing some of the performance issues that you're seeing.

Again, I really appreciate your feedback. I'll keep you posted!.

**Comment by jacobmendoza** [comment]
Hey @rngtng, @sibevin,

That's one of the things that should be working fairly better with the rewrite. A new version is available. Would love to hear your feedback if you have time.

Thank you!
