### ISSUE TITLE
Run single tests

### ISSUE THREAD

**Issue by jmorais** [Jacob84/rspec-tree-runner#7]
A feature that I would appreciate is the possibility to run a single test. The cursor is used to select a test to run and with a keystroke (ctrl-alt-r, for example) would run only that test.

I can make this feature, if needed.

**Comment by jacobmendoza** [comment]
Absolutely, this feature is a must that I have been putting off due to lack of time. If you are interested, that'd be great.

Let me know if you start with it and of course, do not hesitate to ask for whatever you need!.

Thanks a lot for your help,

**Comment by jmorais** [comment]
Ok, will start today!

**Comment by jmorais** [comment]
@jacobmendoza Hey, almost done. Just one problem (two, I guess):

I already did the methods to run a single test. But there's this problem: 

![screen shot 2015-06-29 at 7 26 11 pm](https://cloud.githubusercontent.com/assets/556684/8420805/f3f5471c-1e94-11e5-83c7-96ce0155d63f.png)

I ran just "populates an array of clients" test. And it works, but other tests appear as "passed". I can't find where to fix this. Any suggestion?

The other problem is I don't know how to do proper spec in coffeescript. Is it ok if I just push my solution and you test it?

**Comment by jacobmendoza** [comment]
Hi @jmorais,

Fantastic!. Yeah, don't worry, push your changes. I'll change to your branch and try to figure out what is going on. Also, I will review the tests and adapt them to support the new feature.

I'll keep you informed! :)

**Comment by jacobmendoza** [comment]
Thank you very much!

I'd need two days to review the changes. I'll let you know if I have questions :+1:

**Comment by jacobmendoza** [comment]
Hi @jmorais,

I'm sorry it took so long!. I have solved the issue, added a regression test (among other things). I'm going to review other issues and will publish a new version in a few days. I've included your name in the readme.md. 

Thank you so much for your help :).
